# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('When', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvacuationCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CenterName', models.CharField(max_length=128)),
                ('Address', models.TextField()),
                ('Limit', models.IntegerField(default=100)),
                ('Photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=128)),
                ('EconomicStatus', models.CharField(blank=True, max_length=32, null=True)),
                ('HouseNumber', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncidentName', models.CharField(max_length=32)),
                ('DateOccured', models.DateTimeField(auto_now_add=True)),
                ('Photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=32)),
                ('MiddleName', models.CharField(max_length=32)),
                ('LastName', models.CharField(max_length=32)),
                ('Birthday', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('BloodType', models.CharField(max_length=4)),
                ('Photo', models.ImageField(null=True, upload_to='')),
                ('Contact', models.CharField(max_length=32)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Vulnerabilities', models.TextField(blank=True, null=True)),
                ('NationalIdNumber', models.CharField(blank=True, max_length=128, null=True)),
                ('IsHead', models.BooleanField(default=False)),
                ('Gender', models.CharField(default='MALE', max_length=8)),
                ('EducationalAttainment', models.CharField(blank=True, max_length=64, null=True)),
                ('CivilStatus', models.CharField(default='SINGLE', max_length=64)),
                ('Occupation', models.CharField(blank=True, max_length=64, null=True)),
                ('Allergies', models.CharField(blank=True, max_length=64, null=True)),
                ('MedicalCondition', models.CharField(blank=True, max_length=64, null=True)),
                ('MedicineRequired', models.CharField(blank=True, max_length=64, null=True)),
                ('_Household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rescueapp.Household')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='Center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='rescueapp.EvacuationCenter'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='Incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='rescueapp.Incident'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='rescueapp.Person'),
        ),
    ]
