# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvacuationCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerName', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('limit', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentName', models.CharField(max_length=32)),
                ('dateOccured', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=32)),
                ('middleName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('birthday', models.DateField()),
                ('bloodType', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='rescueapp.EvacuationCenter'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='rescueapp.Incident'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='rescueapp.Person'),
        ),
    ]
