# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('When', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvacuationCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CenterName', models.CharField(max_length=128)),
                ('Address', models.TextField()),
                ('Limit', models.IntegerField(default=100)),
                ('Photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncidentName', models.CharField(max_length=32)),
                ('DateOccured', models.DateTimeField(auto_now_add=True)),
                ('Photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=32)),
                ('MiddleName', models.CharField(max_length=32)),
                ('LastName', models.CharField(max_length=32)),
                ('Birthday', models.DateTimeField(blank=True, null=True)),
                ('BloodType', models.CharField(max_length=4)),
                ('Address', models.TextField(blank=True, default='')),
                ('Photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='Center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='rescueapp.EvacuationCenter'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='Incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='rescueapp.Incident'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='rescueapp.Person'),
        ),
    ]
