# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='NationalIdNumber',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
