# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0002_auto_20170919_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Birthday',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
