# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0002_auto_20170921_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barangay', models.CharField(max_length=24)),
                ('HouseholdNumber', models.IntegerField()),
                ('Category', models.CharField(max_length=16)),
                ('Location', models.CharField(max_length=16)),
                ('Address', models.TextField()),
                ('Photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Members',
        ),
        migrations.AddField(
            model_name='person',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='IDNumber',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='IsHead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='Sex',
            field=models.CharField(default='FEMALE', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Vulnerabilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Sickness',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='_Household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rescueapp.Household'),
        ),
    ]
