# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0002_auto_20170921_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=128)),
                ('EconomicStatus', models.CharField(blank=True, max_length=32, null=True)),
                ('HouseNumber', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Members',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Sickness',
        ),
        migrations.AddField(
            model_name='person',
            name='Allergies',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='CivilStatus',
            field=models.CharField(default='SINGLE', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='EducationalAttainment',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Gender',
            field=models.CharField(default='MALE', max_length=8),
        ),
        migrations.AddField(
            model_name='person',
            name='IsHead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='MedicalCondition',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='MedicineRequired',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='NationalIdNumber',
            field=models.CharField(blank=True, default='None', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='Occupation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Vulnerabilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='_Household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rescueapp.Household'),
        ),
    ]
