# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0003_auto_20170917_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
