# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0003_is_active_default_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='_Center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rescueapp.EvacuationCenter'),
        ),
    ]
