# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0004_person_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
