# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0004_person_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='center',
            new_name='Center',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='incident',
            new_name='Incident',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='person',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='when',
            new_name='When',
        ),
        migrations.RenameField(
            model_name='evacuationcenter',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='evacuationcenter',
            old_name='centerName',
            new_name='CenterName',
        ),
        migrations.RenameField(
            model_name='evacuationcenter',
            old_name='limit',
            new_name='Limit',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='dateOccured',
            new_name='DateOccured',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='incidentName',
            new_name='IncidentName',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='bloodType',
            new_name='BloodType',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='firstName',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lastName',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='middleName',
            new_name='MiddleName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.AddField(
            model_name='person',
            name='Birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
