# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0005_added_isOwned_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='Photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
