# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0006_auto_20170918_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
