# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0007_auto_20170918_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Birthday',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
