# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0007_latlong_evacuation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacuationcenter',
            name='Latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evacuationcenter',
            name='Longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
    ]
