# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0009_fix_latlong_length_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='NamePrefix',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='NameSuffix',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
