# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0010_name_prefix_suffix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='EconomicStatus',
            new_name='HouseCategory',
        ),
        migrations.RemoveField(
            model_name='household',
            name='IsOwned',
        ),
        migrations.AddField(
            model_name='household',
            name='IsEarthquakeProne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='household',
            name='IsFloodProne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='household',
            name='IsSafeZone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='household',
            name='IsStormSurgeProne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='household',
            name='IsTsunamiProne',
            field=models.BooleanField(default=False),
        ),
    ]
