# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0011_change_household_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='HouseOwnership',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
