# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0012_household_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='HouseOwnership',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
