# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0013_change_household_model2'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationcenter',
            name='Amenities',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='InCharge',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='InChargeCellphone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
