# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0014_evac_changes'),
        ('rescueapp', '0007_name_prefix_suffix'),
    ]

    operations = [
    ]
