# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0015_merged_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, max_length=16, null=True)),
                ('Household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescueapp.Household')),
                ('Incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescueapp.Incident')),
            ],
        ),
        migrations.CreateModel(
            name='PersonStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, max_length=16, null=True)),
                ('Incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescueapp.Incident')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescueapp.Person')),
            ],
        ),
    ]
