# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0017_model_changes_reporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='Status',
            field=models.CharField(blank=True, default='safe', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='householdstatus',
            name='Status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='personstatus',
            name='Status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
