# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0020_added_incident_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='EarthquakeEpicenter',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='EarthquakeMagnitude',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='TyphoonSignal',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
