# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0021_incident_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationcenter',
            name='Barangay',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='City',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='Municipality',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='Province',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='evacuationcenter',
            name='Amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evacuationcenter',
            name='InCharge',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='evacuationcenter',
            name='InChargeCellphone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
